portfolio_core:
    resource: "@PortfolioCoreBundle/Resources/config/routing.yml"
    prefix:   /

app_web:
    resource: "@AppWebBundle/Resources/config/routing.yml"
    prefix:   /

app_admin:
    resource: "@AppAdminBundle/Resources/config/routing.yml"
    prefix:   /

app_core:
    resource: "@AppCoreBundle/Resources/config/routing.yml"
    prefix:   /

# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation
