<?php

namespace Portfolio\CoreBundle\Repository;

use Portfolio\CoreBundle\Entity\About;

/**
 * AboutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutRepository extends \Doctrine\ORM\EntityRepository
{
	public function create() {
        return new About;
    }

    public function findAbout()
    {
        return $this->createQueryBuilder('e')
                ->select('e','i')
                ->leftJoin('e.profil', 'i')
                ->orderBy('e.id', 'DESC')
                ->setMaxResults(1)
				->getQuery()
                ->getOneOrNullResult();
    }
    public function findEntities()
    {
        return $this->createQueryBuilder('e')
                ->select('e')
                ->orderBy('e.id', 'DESC')
                ->getQuery()
                ->getResult();
    }
}
