<?php

namespace Portfolio\CoreBundle\Repository;
use Portfolio\CoreBundle\Entity\Cv;
/**
 * CvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvRepository extends \Doctrine\ORM\EntityRepository
{
	public function create() {
        return new Cv;
    }

    public function findCv()
    {
        return $this->createQueryBuilder('e')
                ->select('e','f')
                ->leftJoin('e.fichier', 'f')
                ->orderBy('e.id', 'DESC')
                ->setMaxResults(1)
                ->getQuery()
                ->getOneOrNullResult();
    }
    public function findEntities()
    {
        return $this->createQueryBuilder('e')
                ->select('e')
                ->orderBy('e.id', 'DESC')
                ->getQuery()
                ->getResult();
    }
}
