Portfolio\CoreBundle\Entity\Image:
    type:  entity
    repositoryClass: Portfolio\CoreBundle\Repository\ImageRepository
    table: ps_image
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: true
        updatedAt:
            column: updated_at
            type: datetime