<?php

namespace App\CoreBundle\Repository;

/**
 * DechetImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DechetImageRepository extends \Doctrine\ORM\EntityRepository
{
}
