<?php

namespace App\CoreBundle\Repository;

/**
 * DechetPartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DechetPartenaireRepository extends \Doctrine\ORM\EntityRepository
{
}
