<?php

namespace App\CoreBundle\Repository;

use App\CoreBundle\Entity\Dechet;
/**
 * DechetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DechetRepository extends \Doctrine\ORM\EntityRepository
{
    public function create() {
        return new Dechet;
    }

    public function findEntities($key = null)
    {
        $query = $this->createQueryBuilder('e')
                ->select('e')
                ->orderBy('e.id', 'DESC');
                if(null !== $key){
                    $query->where('e.name LIKE :key')
                        ->setParameter('key', '%'.$key.'%');
                }

        return $query->getQuery()->getResult();
    }
 
    public function getLatestPost()
    {
        return $this->createQueryBuilder('e')
            ->andWhere('e.enabled = :enabled')
            ->setParameter('enabled', 1)
            ->orderBy('e.createdAt', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findEntityBySlug($slug)
    {
        return $this->createQueryBuilder('e')
                ->select('e','e_i')
                ->leftJoin('e.dechetImage', 'e_i')
                ->where('e.slug = :slug')
                ->setParameter('slug', $slug)           
                ->getQuery()
                ->getOneOrNullResult();
    }

    public function findFilter($filter)
    {
        return $this->createQueryBuilder('e')
                ->select('e')
                ->where('e.'.$filter.' = :filter')
                ->setParameter('filter', 0) 
                ->orderBy('e.id', 'DESC')
                ->getQuery()
                ->getResult();
    }

    public function filterAll($filter)
    {
        return $this->createQueryBuilder('e')
                    ->update()
                    ->set('e.'.$filter, 1)
                    ->where('e.'.$filter.' = :filter')
                    ->setParameter('filter', false)
                    ->getQuery()
                    ->getResult();
    }

    public function deleteAll($filter)
    {
        return $this->createQueryBuilder('e')
                    ->where('e.'.$filter.' = :filter')
                    ->setParameter('filter', false)
                    ->delete()
                    ->getQuery()
                    ->execute();
    }
    public function findLatest($limit = null)
    {
        $query = $this->createQueryBuilder('e')
                ->select('e','i')
                ->leftJoin('e.dechetImage', 'i')
                ->orderBy('e.id', 'DESC');

                if(!$limit){
                    $query->setMaxResults($limit);
                }
        return $query->getQuery()->getResult();
    }

    public function countAll()
    {
        return $this
            ->createQueryBuilder('e')
            ->select('COUNT(e.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
    public function search($key)
    {
        return $this->createQueryBuilder('e')
                ->select('e','i')
                ->leftJoin('e.dechetImage', 'i')
                ->orderBy('e.id', 'DESC')
                ->where('e.enabled = 1')
                ->andWhere('e.name LIKE :key')
                ->setParameter('key', '%'.$key.'%')
                ->getQuery()->getResult();
    }
}
