<?php

namespace App\CoreBundle\Repository;

/**
 * NewsVideoWebmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsVideoWebmRepository extends \Doctrine\ORM\EntityRepository
{
}
