<?php

namespace App\CoreBundle\Repository;

/**
 * NewsOtherImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsOtherImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
