<?php

namespace App\CoreBundle\Repository;

/**
 * NewsVideoMp4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsVideoMp4Repository extends \Doctrine\ORM\EntityRepository
{
}
