<?php

namespace App\CoreBundle\Repository;

/**
 * NewsPdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsPdfRepository extends \Doctrine\ORM\EntityRepository
{
}
