<?php

namespace App\CoreBundle\Repository;

use App\CoreBundle\Entity\News;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function create() {
        return new News;
    }

    public function findEntities($key = null)
    {
        $query = $this->createQueryBuilder('e')
                ->select('e')
                ->orderBy('e.id', 'DESC')
                ->where('e.enabled = 1');
                if(null !== $key){
                    $query->where('e.title LIKE :key')
                        ->setParameter('key', '%'.$key.'%');
                }

        return $query->getQuery()->getResult();
    }

   public function findEntityBySlug($slug)
    {
        return $this->createQueryBuilder('e')
                ->select('e','e_i', 'e_o_i', 'mp4', 'ogg', 'webm', 'pdf', 'zip')
                ->leftJoin('e.newsImage', 'e_i')
                ->leftJoin('e.newsOtherImages', 'e_o_i')
                ->leftJoin('e.newsVideoMp4', 'mp4')
                ->leftJoin('e.newsVideoOgg', 'ogg')
                ->leftJoin('e.newsVideoWebm', 'webm')
                ->leftJoin('e.newsPdf', 'pdf')
                ->leftJoin('e.newsZip', 'zip')
                ->where('e.slug = :slug')
                ->setParameters(['slug' => $slug])           
                ->getQuery()
                ->getOneOrNullResult();
    }

    public function filterAll($filter)
    {
        return $this->createQueryBuilder('e')
                    ->update()
                    ->set('e.'.$filter, 1)
                    ->where('e.'.$filter.' = :filter')
                    ->setParameter('filter', false)
                    ->getQuery()
                    ->getResult();
    }

    public function deleteAll($filter)
    {
        return $this->createQueryBuilder('e')
                    ->where('e.'.$filter.' = :filter')
                    ->setParameter('filter', false)
                    ->delete()
                    ->getQuery()
                    ->execute();
    }

    public function findLatest($limit)
    {
        return $this->createQueryBuilder('e')
                ->select('e','i')
                ->leftJoin('e.newsImage', 'i')
                ->orderBy('e.id', 'DESC')
                ->setMaxResults($limit)
                ->getQuery()->getResult();
    }

    public function findList($limit)
    {
        return $this->createQueryBuilder('e')
                ->select('e')
                ->orderBy('e.id', 'DESC')
                ->setMaxResults($limit)
                ->getQuery()->getResult();
    }

    public function findEntity()
    {
        return $this->createQueryBuilder('e')
                ->select('e','e_i', 'e_o_i', 'mp4', 'ogg', 'webm', 'pdf', 'zip')
                ->leftJoin('e.newsImage', 'e_i')
                ->leftJoin('e.newsOtherImages', 'e_o_i')
                ->leftJoin('e.newsVideoMp4', 'mp4')
                ->leftJoin('e.newsVideoOgg', 'ogg')
                ->leftJoin('e.newsVideoWebm', 'webm')
                ->leftJoin('e.newsPdf', 'pdf')
                ->leftJoin('e.newsZip', 'zip')
                ->orderBy('e.id', 'DESC')
                ->where('e.enabled = :enabled')
                ->setParameter('enabled', 1)
                ->getQuery()->getResult();
    }
    public function countAll()
    {
        return $this
            ->createQueryBuilder('e')
            ->select('COUNT(e.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
