<?php

namespace App\CoreBundle\Repository;

/**
 * NewsVideoOggRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsVideoOggRepository extends \Doctrine\ORM\EntityRepository
{
}
