<?php

namespace App\CoreBundle\Repository;

/**
 * NewsZipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsZipRepository extends \Doctrine\ORM\EntityRepository
{
}
