<?php

namespace App\CoreBundle\Repository;

/**
 * PageImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageImageRepository extends \Doctrine\ORM\EntityRepository
{
}
