<?php

namespace App\CoreBundle\Repository;

/**
 * PageOtherImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageOtherImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
