<?php

namespace App\CoreBundle\Repository;

use App\CoreBundle\Entity\Page;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function create() {
        return new Page;
    }

    public function findEntities($key = null)
    {
        $query = $this->createQueryBuilder('e')
                ->select('e')
                ->orderBy('e.id', 'DESC');
                if(null !== $key){
                    $query->where('e.title LIKE :key')
                        ->setParameter('key', '%'.$key.'%');
                }

        return $query->getQuery()->getResult();
    }

   public function findEntityBySlug($slug)
    {
        return $this->createQueryBuilder('e')
                ->select('e','e_i', 'e_o_i')
                ->leftJoin('e.pageImage', 'e_i')
                ->leftJoin('e.pageOtherImages', 'e_o_i')
                ->where('e.slug = :slug')
                ->setParameters(['slug' => $slug])           
                ->getQuery()
                ->getOneOrNullResult();
    }

    public function findList($limit)
    {
        return $this->createQueryBuilder('e')
                ->select('e')
                ->orderBy('e.id', 'DESC')
                ->setMaxResults($limit)
                ->getQuery()->getResult();
    }

    public function findFilter($filter)
    {
        return $this->createQueryBuilder('e')
                ->select('e')
                ->where('e.'.$filter.' = :filter')
                ->setParameter('filter', 0) 
                ->orderBy('e.id', 'DESC')
                ->getQuery()
                ->getResult();
    }

    public function filterAll($filter)
    {
        return $this->createQueryBuilder('e')
                    ->update()
                    ->set('e.'.$filter, 1)
                    ->where('e.'.$filter.' = :filter')
                    ->setParameter('filter', false)
                    ->getQuery()
                    ->getResult();
    }

    public function deleteAll($filter)
    {
        return $this->createQueryBuilder('e')
                    ->where('e.'.$filter.' = :filter')
                    ->setParameter('filter', false)
                    ->delete()
                    ->getQuery()
                    ->execute();
    }
    public function countAll()
    {
        return $this
            ->createQueryBuilder('e')
            ->select('COUNT(e.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}