<?php

namespace App\CoreBundle\Repository;

/**
 * PartenaireLogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaireLogoRepository extends \Doctrine\ORM\EntityRepository
{
}
