<?php

namespace App\CoreBundle\Repository;

/**
 * PartenaireImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaireImageRepository extends \Doctrine\ORM\EntityRepository
{
}
