<?php

namespace App\CoreBundle\Repository;

/**
 * UtilisateurImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurImageRepository extends \Doctrine\ORM\EntityRepository
{
}
