App\CoreBundle\Entity\Commande:
    type: entity
    repositoryClass: App\CoreBundle\Repository\CommandeRepository
    table: commande
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        quantity:
            column: quantity
            type: float
        delais:
            column: delais
            type: datetime
        reason:
            column: reason
            type: string
        token:
            column: token
            type: string
            length: 255
        enabled:
            column: enabled
            type: boolean
            nullable: true
        checked:
            column: checked
            type: boolean
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            column: updated_at
            type: datetime
            type: boolean
            gedmo:
                timestampable:
                    on: update
        slug:
            column: slug
            type: string
            length: 255
            gedmo:
                slug:
                    separator: -
                    style: lower
                    fields:
                       - createdAt

    manyToOne:
        dechet:
            targetEntity: Dechet
            inversedBy: commandes
            joinColumn:
                name: dechet_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
                onUpdate: "CASCADE"
        client:
            targetEntity: Client
            inversedBy: commandes
            joinColumn:
                name: client_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
                onUpdate: "CASCADE"


