App\CoreBundle\Entity\NewsOtherImages:
    type:  entity
    repositoryClass: App\CoreBundle\Repository\NewsOtherImagesRepository
    table: news_other_image
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
        updatedAt:
            column: updated_at
            type: datetime