App\CoreBundle\Entity\NewsVideoWebm:
    type:  entity
    repositoryClass: App\CoreBundle\Repository\NewsVideoWebmRepository
    table: news_video_webm
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
        extension:
            column: extension
            type: string
            length: 255
        mimeType:
            column: mime_type
            type: string
            length: 255
        size:
            column: size
            type: integer
        updatedAt:
            column: updated_at
            type: datetime