App\CoreBundle\Entity\Page:
    type: entity
    repositoryClass: App\CoreBundle\Repository\PageRepository
    table: page
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            column: title
            type: string
            length: 255
        content:
            column: content
            type: text
        metaTitle:
            column: meta_title
            type: string
            length: 255
            nullable: true
        metaDescription:
            column: meta_description
            type: string
            length: 255
        metaKeywords:
            column: meta_keywords
            type: string
            length: 255
            nullable: true
        slug:
            column: slug
            type: string
            length: 255
            gedmo:
                slug:
                    separator: -
                    style: lower
                    fields:
                       - title
        token:
            column: token
            type: string
            length: 255

        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            column: updated_at
            type: datetime
            type: boolean
            gedmo:
                timestampable:
                    on: update
        enabled:
            column: enabled
            type: boolean
            nullable: true

    oneToOne:
        pageImage:
            targetEntity: PageImage
            cascade: [ persist ]
            orphanRemoval: true

    manyToOne:
        user:
            targetEntity: Utilisateur
            inversedBy: pages
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
                onUpdate: "CASCADE"

    manyToMany:
        pageOtherImages:
            targetEntity: PageOtherImages
            cascade: ["persist", "remove"]
            inversedBy: pages
            joinTable:
                name: other_images_page
                joinColumns:
                    page_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    page_other_images_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"

    lifecycleCallbacks:
        prePersist: [ setMetaTitleValue, setMetaDescriptionValue, setMetaKeysValue ]
