App\CoreBundle\Entity\PartenaireLogo:
    type:  entity
    repositoryClass: App\CoreBundle\Repository\PartenaireLogoRepository
    table: partenaire_logo
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
        updatedAt:
            column: updated_at
            type: datetime